site_name: "Nikiforova Anna K33421"
theme:
  name: material
  features:
    - navigation.indexes
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Переключиться на тёмную тему
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Переключиться на светлую тему
  language: ru
repo_url: https://github.com/AnnaNik334743/
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False
nav:
  - Home: index.md
  - Lab 1:
      - Intro: lab1/intro.md
      - Body: lab1/body.md
      - Conclusion: lab1/conclusion.md
  - Lab 2:
      - Intro: lab2/intro.md
      - Task1: lab2/task1.md
      - Task2: lab2/task2.md
      - Conclusion: lab2/conclusion.md
